/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class ReporteEstadisticoVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReporteEstadisticoVista.class.getName());

    /**
     * Creates new form ReporteEstadisticoVista
     */
    public ReporteEstadisticoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblIDReporteE = new javax.swing.JLabel();
        TxtIDReporteE = new javax.swing.JTextField();
        cmbxNombreDesarrollador = new javax.swing.JComboBox<>();
        lblNombreDesarrollador = new javax.swing.JLabel();
        cmbxProyectos = new javax.swing.JComboBox<>();
        lblNombreDesarrollador1 = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        lblEstadoProyecto = new javax.swing.JLabel();
        txtFechaFin1 = new javax.swing.JTextField();
        cmbxEstadoProyecto = new javax.swing.JComboBox<>();
        btnPrevisualizar = new javax.swing.JButton();
        btnGenerarPDF = new javax.swing.JButton();
        panelGrafico = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnIrMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Generar Reporte  Estadístico");

        lblIDReporteE.setText("ID Reporte Estadístico:  ");

        TxtIDReporteE.setEditable(false);

        cmbxNombreDesarrollador.addActionListener(this::cmbxNombreDesarrolladorActionPerformed);

        lblNombreDesarrollador.setText("Nombre del Desarrollador: ");

        lblNombreDesarrollador1.setText("Nombre del Proyecto:");

        lblFechaInicio.setText("Fecha inicio:");

        lblFechaFin.setText("Fecha Fin:");

        lblEstadoProyecto.setText("Elija el estado del proyecto");

        cmbxEstadoProyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Finalizado" }));

        btnPrevisualizar.setText("Previsualizar ");

        btnGenerarPDF.setText("Generar PDF");

        panelGrafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGrafico.setPreferredSize(new java.awt.Dimension(560, 260));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        btnIrMenu.setText("Ir al Menú");
        btnIrMenu.addActionListener(this::btnIrMenuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNombreDesarrollador1)
                        .addComponent(lblNombreDesarrollador)
                        .addComponent(lblIDReporteE)
                        .addComponent(lblFechaInicio)
                        .addComponent(lblFechaFin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstadoProyecto)
                        .addGap(17, 17, 17))
                    .addComponent(btnPrevisualizar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbxNombreDesarrollador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtIDReporteE, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbxProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFechaFin1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFechaInicio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbxEstadoProyecto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnGenerarPDF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnIrMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDReporteE)
                            .addComponent(TxtIDReporteE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxNombreDesarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreDesarrollador))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreDesarrollador1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxEstadoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstadoProyecto))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaInicio)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaFin)
                            .addComponent(txtFechaFin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrevisualizar)
                            .addComponent(btnGenerarPDF))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar)
                            .addComponent(btnIrMenu))
                        .addGap(31, 31, 31))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbxNombreDesarrolladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxNombreDesarrolladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxNombreDesarrolladorActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIrMenuActionPerformed

    // ─────── Getters para el controlador (sin lógica de negocio) ───────
    public javax.swing.JComboBox<modelo.Proyecto> getCmbxProyectos() {
        return cmbxProyectos;
    }

    public javax.swing.JComboBox<modelo.Recurso> getCmbxNombreDesarrollador() {
        return cmbxNombreDesarrollador;
    }

    public javax.swing.JComboBox<String> getCmbxEstadoProyecto() {
        return cmbxEstadoProyecto;
    }


    public javax.swing.JTextField getTxtFechaInicio() {
        return txtFechaInicio;
    }

    public javax.swing.JTextField getTxtFechaFin() {
        return txtFechaFin1;
    }

    public javax.swing.JTextField getTxtIDReporteE() {
        return TxtIDReporteE;
    }

    public javax.swing.JButton getBtnPrevisualizar() {
        return btnPrevisualizar;
    }

    public javax.swing.JButton getBtnGenerarPDF() {
        return btnGenerarPDF;
    }

    public javax.swing.JButton getBtnRegresar() {
        return btnRegresar;
    }

    public javax.swing.JButton getBtnIrMenu() {
        return btnIrMenu;
    }

    public javax.swing.JPanel getPanelGrafico() {
        return panelGrafico;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form (levanta el controlador para que funcione en Run File) */
        java.awt.EventQueue.invokeLater(() -> {
            ReporteEstadisticoVista ventana = new ReporteEstadisticoVista();
            new controlador.ReporteEstadisticoControlador(ventana);
            ventana.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtIDReporteE;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnIrMenu;
    private javax.swing.JButton btnPrevisualizar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbxEstadoProyecto;
    private javax.swing.JComboBox<modelo.Recurso> cmbxNombreDesarrollador;
    private javax.swing.JComboBox<modelo.Proyecto> cmbxProyectos;
    private javax.swing.JLabel lblEstadoProyecto;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblIDReporteE;
    private javax.swing.JLabel lblNombreDesarrollador;
    private javax.swing.JLabel lblNombreDesarrollador1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JTextField txtFechaFin1;
    private javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
