/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class ReporteVista extends javax.swing.JFrame {
    
    /**
     * Creates new form ReporteVista
     */
    public ReporteVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbHojas = new javax.swing.JComboBox<>();
        btnSeleccionarRuta = new javax.swing.JButton();
        btnGenerarPDF = new javax.swing.JButton();
        txtHojaId = new javax.swing.JTextField();
        txtRecursoId = new javax.swing.JTextField();
        lblIdHoja = new javax.swing.JLabel();
        lblProgramador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbnNombreDev = new javax.swing.JComboBox<>();
        lblNombreDev = new javax.swing.JLabel();
        lblHoja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbHojas.setModel(new javax.swing.DefaultComboBoxModel<modelo.HojaTiempo>());

        btnSeleccionarRuta.setText("Seleccionar Ruta");

        btnGenerarPDF.setText("Generar PDF");

        lblIdHoja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIdHoja.setText("ID Hoja:");

        lblProgramador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProgramador.setText("ID Programador:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Generar Reporte ");

        lblNombreDev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreDev.setText("Nombre:");

        lblHoja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoja.setText("Hoja:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdHoja, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProgramador)
                    .addComponent(lblNombreDev)
                    .addComponent(lblHoja))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(274, 274, 274))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHojaId, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbnNombreDev, 0, 216, Short.MAX_VALUE)
                            .addComponent(cmbHojas, 0, 216, Short.MAX_VALUE)
                            .addComponent(txtRecursoId))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnSeleccionarRuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarPDF)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHojaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdHoja))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramador)
                    .addComponent(txtRecursoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbnNombreDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreDev))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarRuta)
                    .addComponent(btnGenerarPDF))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JComboBox<modelo.HojaTiempo> getCmbHojas() {
        return cmbHojas;
    }

    public javax.swing.JComboBox<modelo.Recurso> getCmbnNombreDev() {
        return cmbnNombreDev;
    }

    public javax.swing.JButton getBtnSeleccionarRuta() {
        return btnSeleccionarRuta;
    }

    public javax.swing.JButton getBtnGenerarPDF() {
        return btnGenerarPDF;
    }

    public javax.swing.JTextField getTxtHojaId() {
        return txtHojaId;
    }

    public javax.swing.JTextField getTxtRecursoId() {
        return txtRecursoId;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnSeleccionarRuta;
    private javax.swing.JComboBox<modelo.HojaTiempo> cmbHojas;
    private javax.swing.JComboBox<modelo.Recurso> cmbnNombreDev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHoja;
    private javax.swing.JLabel lblIdHoja;
    private javax.swing.JLabel lblNombreDev;
    private javax.swing.JLabel lblProgramador;
    private javax.swing.JTextField txtHojaId;
    private javax.swing.JTextField txtRecursoId;
    // End of variables declaration//GEN-END:variables
}
